import { Action } from "redux";

export interface BaseAction<T = any> extends Action<string> {
  payload?: T;
};

export const actionsEnums = {
  POKEMON_REQUEST_STARTED: 'POKEMON_REQUEST_STARTED',
  POKEMON_REQUEST_COMPLETED: 'POKEMON_REQUEST_COMPLETED',
  FILTER_POKEMONS: 'FILTER_POKEMONS',
  REQUEST_SINGLE_POKEMON_STARTED: 'REQUEST_SINGLE_POKEMON_STARTED',
  REQUEST_SINGLE_POKEMON_COMPLETED: 'REQUEST_SINGLE_POKEMON_COMPLETED'
}